// obfuscate guest list before pasting into HTML file
// https://obfuscator.io/
// make sure guest names are not readable

const INVITADOS = {
	"pk9fRL": "MARISA e MIGUEL",
	"Len73j": "AMELIA",
	"wCwP3E": "PAULO e DOLORES",
	"2kpqPN": "BERTA e RAMON",
	"Pn4aEX": "MARISA",
	"pYWR5p": "MARGA, TOMÁS e PEDRO",
	"5vENWm": "IGNACIO, MARTA, MARTÍN e PABLO",
	"vN5eTH": "ROSENDO, PURI e CARLOS",
	"wAsa6H": "JOSÉ, BEA, MARÍA e FÁTIMA",
	"2n9ZDu": "PILAR e CARLOS",
	"Fam9Fn": "SANTI, ALICIA, IAGO e LUCÍA",
	"7nWtaA": "MARI e ALBERTO",
	"AbkE6q": "MARTA, RAFA e MATEO",
	"Z3rGAk": "CHISCO e ARI",
	"8HBvBr": "ORQUÍDEA e JOSÉ",
	"RpF6Xj": "ISA",
	"MaS4TQ": "MARY LUZ e GUILLE",
	"d6Dwez": "GIOVANNI e STEFANI",
	"fWs5Y4": "SILVIA",
	"UrWz7r": "MANUEL e VINICIUS",
	"F36KeJ": "DIEGO e PAULA",
	"Y3Fyv6": "JOAQUÍN e LARA",
	"d6qGWm": "MIGUEL e UXÍA",
	"Ryet4d": "ELOY e SONIA",
	"9cH75g": "JULIÁN e MELANIE",
	"6Ar2TW": "LORENZO",
	"c7ZfxF": "COUTO",
	"e7vsVg": "ALMUIÑA",
	"Yec7RL": "SANTI",
	"3kSzSt": "JACOBO",
	"7p6Dg2": "ROQUE",
	"NyKT4q": "DIEGO",
	"sKK2ak": "ABEL",
	"6gRDuB": "NEREA",
	"P7NnzG": "CARLA",
	"4L2Ek8": "NOELIA",
	"aH8Wy8": "APERADOR",
	"jdpT68": "KEVIN",
	"r3YPtN": "ALICIA",
	"pJR3yC": "CARMEN",
	"aXAv5k": "CARMELA",
	"W7Ahak": "FRAN, EVA, MARCELO e NICOLAU",
	"pw6Cvk": "ALEJANDRO, CARMELA e TEO",
	"u8Gd5T": "MARÍA e LUCIANO",
	"Yey3ZZ": "DINA e SANTI",
	"Dy3fW3": "ABRAHAM",
	"3HVbky": "SAMUEL",
	"testtt": "TEST"
};